version: "3.7"
services:
  wishlist-backend:
    container_name: wishlist-backend
    image: wishlist_backend
    build:
      context: ./wishlists-backend
      dockerfile: Dockerfile
    networks:
      - wishlist-net
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:6.0.5
    env_file: .env
    networks:
      - wishlist-net
    ports:
      - 27017:27017
    volumes:
      - mongodb:/usr/data/mongo-data

networks:
  wishlist-net:
    driver: bridge

volumes:
  mongodb:
