version: '3.7'
services:
  wishlist-backend:
    container_name: wishlist_backend
    image: wishlist_backend
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image:  mongo:6.0.5
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: patata
      MONGO_INITDB_ROOT_PASSWORD: patataPsswd
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db